[package]
name = "xmc4200"
description = "Peripheral access library for XCM4200 ARM Cortex-M"
version = "0.1.0"
authors = ["Lucas Brendel <lucasbrendel@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/lucasbrendel/xmc4200"
keywords = ["cortex-m", "infineon", "arm", "xmc4x"]
documentation = "https://docs.rs/xmc4200/"

[dependencies]
cortex-m = "0.3.0"
bare-metal = "0.1.1"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.3.0"

[features]
rt = ["cortex-m-rt"]
